spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://106.52.83.177/mydata?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

server:
  context-path: /coolparking


